#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
	;}


mkgitignore() {
  if [ -z "$1" ]; then
    echo "Usage: mkgitignore <language>"
    curl -s https://api.github.com/repos/github/gitignore/contents | \
      jq -r '.[] | .name' | sed 's/.gitignore//'
    return 1
  fi
  name="${1[1]:u}${1:1}"
  curl -L -o .gitignore "https://raw.githubusercontent.com/github/gitignore/main/$name.gitignore"
;}

arxiv() {
  if [ -z "$1" ]; then
    echo "Usage: arxiv <arXiv ID>"
    return 1
  fi
  arxiv_id="$(basename $1 .pdf)"
  curl -s "https://export.arxiv.org/api/query?id_list=$arxiv_id&max_results=1" | xmlstarlet sel -N atom="http://www.w3.org/2005/Atom" -t -m "//atom:entry[1]/atom:title" -v . -n
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
# alias \
# 	ls="ls -hN --color=auto --group-directories-first" \
# 	grep="grep --color=auto" \
# 	diff="diff --color=auto" \
# 	ccat="highlight --out-format=ansi" \
# 	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"
