live_config_reload = true

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
  # "~/.config/alacritty/themes/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/themes/monokai.toml"
  # "~/.config/alacritty/themes/themes/nord.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 16

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 12
y = 12

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"
